name: Auto Build Patch
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: my-code
      - name: Prepare Build Environment
        run: git clone https://github.com/ReVanced/revanced-patches-template.git builder
      - name: Inject Kotlin Code
        run: |
          mkdir -p builder/patches/src/main/kotlin
          cp -r my-code/src/main/kotlin/* builder/patches/src/main/kotlin/
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Patches
        working-directory: builder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x gradlew
          ./gradlew build
          find patches/build/ -name "*.jar" -exec cp {} ../ \;
          find patches/build/ -name "*.json" -exec cp {} ../ \;
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: VeePN Patch
          files: |
            *.jar
            *.json
